### ISSUE TITLE
Cache reset when use with react route

### ISSUE THREAD

**Issue by vinks** [RyanRoll/react-use-api#8]
Hi, when we use react-router, and route changed, ApiProvider resets cache and after return to the previous route data will be refetched. Can we manual control cache key resets for this?

**Comment by RyanRoll** [comment]
Did your problem occur in SSR or client?
It sounds like your ApiProvider is under Router Provider, can you reverse the two and try it out?
For example,
```tsx
<ApiProvider context={apiContext}>
  <StaticRouter location={url} context={routerContext}>
    <App />
  </StaticRouter>
</ApiProvider>
```
